version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: helpdesk-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'helpdesk_db'
      MYSQL_USER: 'helpdesk_user'
      MYSQL_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: helpdesk-phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: '1234'
    depends_on:
      - db

volumes:
  db_data: